---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: quote-backend
  namespace: ambassador
spec:
  prefix: /backend/
  service: quote
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  quote-backend-canary
spec:
  prefix: /backend/
  service: quote-canary
  weight: 66
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  qotm-backend-shadow
spec:
  prefix: /backend/
  service: qotm-shadow
  shadow: true
