---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: quote-backend
  namespace: ambassador
spec:
  prefix: /backend/
  service: quote
  weight: 90
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  quote-backend-canary
spec:
  prefix: /backend/
  service: quote-canary
  weight: 10
