---
apiVersion: v2
kind: Service
metadata:
  name: quotev2
  namespace: ambassador
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: quotev2
---
apiVersion: apps/v2
kind: Deployment
metadata:
  name: quotev2
  namespace: ambassador
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quotev2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: quotev2
    spec:
      containers:
      - name: backendv2
        image: quay.io/datawire/quote:0.3.0
        ports:
        - name: http
          containerPort: 8080
