---
apiVersion: v1
kind: Service
metadata:
  name: qotm-shadow
  namespace: ambassador
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: qotm-shadow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qotm-shadow
  namespace: ambassador
spec:
  replicas: 4
  selector:
    matchLabels:
      app: qotm-shadow
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: qotm-shadow
    spec:
      containers:
      - name: qotm-shadow
        image: quay.io/datawire/quote:0.3.0
        ports:
        - name: http
          containerPort: 8080
