---
apiVersion: v1
kind: Service
metadata:
  name: quotecanary
  namespace: ambassador
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: quotecanary
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotecanary
  namespace: ambassador
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quotecanary
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: quotecanary
    spec:
      containers:
      - name: quotecanary
        image: quay.io/datawire/quote:0.3.0
        ports:
        - name: http
          containerPort: 8080
